# Generated by Django 5.2.10 on 2026-01-12 17:52

from django.db import migrations, models

def copy_step_to_product_type(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for p in Product.objects.all().only("id", "step", "product_type"):
        if (not p.product_type) or (p.product_type == "unknown"):
            p.product_type = p.step or "unknown"
            p.save(update_fields=["product_type"])

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attrs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('skincare', 'Skincare'), ('haircare', 'Haircare'), ('makeup', 'Makeup'), ('fragrance', 'Fragrance')], db_index=True, default='skincare', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='concerns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='step',
            field=models.CharField(blank=True, choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('spf', 'SPF'), ('mask', 'Mask')], default='', max_length=30),
        ),
        migrations.RunPython(copy_step_to_product_type, migrations.RunPython.noop),
    ]
