# Generated by Django 5.2.10 on 2026-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_application_text_product_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume_raw',
            field=models.TextField(blank=True, default=''),
        ),
    ]
