"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    v = os.getenv(name)
    if v is None:
        return default
    return v.strip().lower() in {"1", "true", "yes", "y", "on"}


def env_csv(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*ptqzd-7zlnf-o66x9!2&-cyxa4+^+1^+y&g5(y8ct^f$vypmk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_csv("ALLOWED_HOSTS", "*")
CSRF_TRUSTED_ORIGINS = env_csv("CSRF_TRUSTED_ORIGINS", "")

SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", False)


# Application definition

INSTALLED_APPS = [
    # Django apps...
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",

    # Local apps
    "catalog",
    "users_app",
    "routines",
    "transactions",
    "offers",
    "loyalty",
    "analytics_app",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "recs_app",
    "checkout_app",
    "audit",
    "admin_tools.apps.AdminToolsConfig",
    "recs_analytics",
    "roadmap_app",
    "gift_cards",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "backend.api_errors.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema"
}
REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
    "rest_framework.throttling.UserRateThrottle",
    "rest_framework.throttling.AnonRateThrottle",
]
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
    "anon": "60/min",
    "user": "240/min",
    "recs": "30/min",
    "next_offer": "20/min",
    "checkout_preview": "30/min",
    "auth_login": os.getenv("AUTH_LOGIN_RATE", "10/min"),
    "auth_register": os.getenv("AUTH_REGISTER_RATE", "5/hour"),
    "auth_password_reset_request": os.getenv("AUTH_PASSWORD_RESET_REQUEST_RATE", "5/hour"),
    "auth_verify_email_resend": os.getenv("AUTH_VERIFY_EMAIL_RESEND_RATE", "10/hour"),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Loyalty Platform API",
    "DESCRIPTION": "Personalized loyalty + recommendations platform",
    "VERSION": "1.0.0",
    # чтобы схема показывала только /api/v1/*
    "SCHEMA_PATH_PREFIX": r"/api",
    # красивее имена параметров pk
    "SCHEMA_COERCE_PATH_PK": True,
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "audit.middleware.RequestIdMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'backend.email_verification_middleware.VerifiedEmailRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "loyalty",
        "USER": "loyalty",
        "PASSWORD": "loyalty",
        "HOST": "127.0.0.1",
        "PORT": "5433",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USE_BUNDLE_TARGETING = env_bool("USE_BUNDLE_TARGETING", True)
USE_POST_PURCHASE_RULES = env_bool("USE_POST_PURCHASE_RULES", True)
USE_ROUTINE_SHORTCUT = env_bool("USE_ROUTINE_SHORTCUT", True)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

AUDIT_RETENTION_DAYS = int(os.getenv("AUDIT_RETENTION_DAYS", "90"))

OFFERS_RETENTION_DAYS = int(os.getenv("OFFERS_RETENTION_DAYS", "180"))
PROFILE_COMPLETION_BONUS_POINTS = int(os.getenv("PROFILE_COMPLETION_BONUS_POINTS", "50"))
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@uilesim.local")
EMAIL_VERIFICATION_MAX_AGE_SECONDS = int(os.getenv("EMAIL_VERIFICATION_MAX_AGE_SECONDS", str(60 * 60 * 24 * 3)))
EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = int(os.getenv("EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS", "60"))
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", str(60 * 60 * 24 * 3)))
WINBACK_INACTIVITY_DAYS = int(os.getenv("WINBACK_INACTIVITY_DAYS", "30"))
WINBACK_REASSIGN_DAYS = int(os.getenv("WINBACK_REASSIGN_DAYS", "30"))
FAVORITE_CATEGORY_WINDOW_DAYS = int(os.getenv("FAVORITE_CATEGORY_WINDOW_DAYS", "90"))
FAVORITE_CATEGORY_REASSIGN_DAYS = int(os.getenv("FAVORITE_CATEGORY_REASSIGN_DAYS", "14"))
OFFER_SUPERSEDE_MAX_EXPOSED = int(os.getenv("OFFER_SUPERSEDE_MAX_EXPOSED", "1"))
ADMIN_METRICS_CACHE_TTL_SECONDS = int(os.getenv("ADMIN_METRICS_CACHE_TTL_SECONDS", "60"))
ADMIN_OVERVIEW_CACHE_TTL_SECONDS = int(os.getenv("ADMIN_OVERVIEW_CACHE_TTL_SECONDS", "60"))

RECS_FATIGUE_WINDOW_DAYS = int(os.getenv("RECS_FATIGUE_WINDOW_DAYS", "14"))
RECS_FATIGUE_IMPRESSIONS_MIN = int(os.getenv("RECS_FATIGUE_IMPRESSIONS_MIN", "6"))
RECS_FATIGUE_HARD_SKIP = os.getenv("RECS_FATIGUE_HARD_SKIP", "1").strip() in {"1","true","yes","on"}

RECS_UPLIFT_CLICK = float(os.getenv("RECS_UPLIFT_CLICK", "0.15"))          # +к score за клик
RECS_UPLIFT_PURCHASE = float(os.getenv("RECS_UPLIFT_PURCHASE", "0.5"))     # +к score за attributed purchase
RECS_PENALTY_IMP = float(os.getenv("RECS_PENALTY_IMP", "0.05"))     

RECS_GLOBAL_WINDOW_DAYS = int(os.getenv("RECS_GLOBAL_WINDOW_DAYS", "30"))
RECS_GLOBAL_MIN_IMP = int(os.getenv("RECS_GLOBAL_MIN_IMP", "20"))

# baseline “нормальная конверсия” (атрибутированная покупка / impression)
RECS_GLOBAL_BASELINE_CR = float(os.getenv("RECS_GLOBAL_BASELINE_CR", "0.02"))

# масштаб и ограничения бонуса
RECS_GLOBAL_SCALE = float(os.getenv("RECS_GLOBAL_SCALE", "6.0"))
RECS_GLOBAL_MAX_UPLIFT = float(os.getenv("RECS_GLOBAL_MAX_UPLIFT", "0.35"))
RECS_GLOBAL_MAX_PENALTY = float(os.getenv("RECS_GLOBAL_MAX_PENALTY", "0.35"))

# если хочется жёстко не брать “мертвое”
RECS_GLOBAL_HARD_SKIP = os.getenv("RECS_GLOBAL_HARD_SKIP", "0").strip().lower() in {"1","true","yes","on"}
RECS_GLOBAL_HARD_SKIP_CR = float(os.getenv("RECS_GLOBAL_HARD_SKIP_CR", "0.002"))  # 0.2%

RECS_ALGO_DEFAULT = os.getenv("RECS_ALGO_DEFAULT", "cooc").strip().lower()
RECS_RERANKER_MODEL_PATH = os.getenv(
    "RECS_RERANKER_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "recs_reranker_goldapple_deep_v2" / "model.pkl").resolve()),
)
ROADMAP_NEXTSTEP_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "roadmap_next_step" / "model.pkl").resolve()),
)
ROADMAP_RUNTIME_FREEZE_ML = env_bool("ROADMAP_RUNTIME_FREEZE_ML", True)
ROADMAP_ML_INVOCATION_LOG_ENABLED = env_bool("ROADMAP_ML_INVOCATION_LOG_ENABLED", True)
ROADMAP_NEXTSTEP_V3_ENABLED = env_bool("ROADMAP_NEXTSTEP_V3_ENABLED", False)
ROADMAP_NEXTSTEP_V3_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V3_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "roadmap_next_step_v3" / "model.pkl").resolve()),
)
ROADMAP_NEXTSTEP_V4_ENABLED = env_bool("ROADMAP_NEXTSTEP_V4_ENABLED", False)
ROADMAP_NEXTSTEP_V4_ENABLED_CATEGORIES = env_csv(
    "ROADMAP_NEXTSTEP_V4_ENABLED_CATEGORIES",
    "skincare,haircare,makeup",
)
ROADMAP_NEXTSTEP_V4_DISABLED_CATEGORIES = env_csv(
    "ROADMAP_NEXTSTEP_V4_DISABLED_CATEGORIES",
    "fragrance",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_ENABLED_CATEGORIES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_ENABLED_CATEGORIES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_PURCHASE_CONTEXT_ONLY_CATEGORIES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_PURCHASE_CONTEXT_ONLY_CATEGORIES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_FORCE_ENABLED_CATEGORIES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_FORCE_ENABLED_CATEGORIES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_MAKEUP_PRODUCT_TYPES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_MAKEUP_PRODUCT_TYPES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_MAKEUP_STEP_INDEXES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_MAKEUP_STEP_INDEXES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_PRODUCT_TYPES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_PRODUCT_TYPES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_STEP_INDEXES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_STEP_INDEXES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_PERCENT = int(
    os.getenv("ROADMAP_NEXTSTEP_V4_PARTIAL_PERCENT", "0")
)
_roadmap_nextstep_v4_partial_makeup_percent_raw = os.getenv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_MAKEUP_PERCENT",
    "",
).strip()
ROADMAP_NEXTSTEP_V4_PARTIAL_MAKEUP_PERCENT = (
    int(_roadmap_nextstep_v4_partial_makeup_percent_raw)
    if _roadmap_nextstep_v4_partial_makeup_percent_raw
    else None
)
_roadmap_nextstep_v4_partial_haircare_percent_raw = os.getenv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_PERCENT",
    "",
).strip()
ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_PERCENT = (
    int(_roadmap_nextstep_v4_partial_haircare_percent_raw)
    if _roadmap_nextstep_v4_partial_haircare_percent_raw
    else None
)
ROADMAP_NEXTSTEP_V4_PARTIAL_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_MODEL_PATH",
    "",
).strip()
ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_MODEL_PATH",
    "",
).strip()
ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_ACTIVE_MODEL_PRODUCT_TYPES = env_csv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_HAIRCARE_ACTIVE_MODEL_PRODUCT_TYPES",
    "",
)
ROADMAP_NEXTSTEP_V4_PARTIAL_SALT = os.getenv(
    "ROADMAP_NEXTSTEP_V4_PARTIAL_SALT",
    "roadmap_nextstep_v4_partial_v1",
).strip()
ROADMAP_NEXTSTEP_V4_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "roadmap_next_step_v4" / "model.pkl").resolve()),
)
ROUTINE_RANKER_MODEL_PATH = os.getenv(
    "ROUTINE_RANKER_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "routine_ranker_v1" / "model.pkl").resolve()),
)

# Offer redemption propensity model (LR pipeline from train_offer_redemption_lr.py).
OFFER_REDEMPTION_MODEL_PATH = os.getenv(
    "OFFER_REDEMPTION_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "offer_redemption_lr_synth_v1" / "model.pkl").resolve()),
)
OFFER_REDEMPTION_ML_ENABLED = env_bool("OFFER_REDEMPTION_ML_ENABLED", True)
# Blend weight: final_score = rule_score + weight * ml_prob * 10.
# 0.0 disables ML contribution (pure rules); 1.0 lets ML add up to +10 to rule score.
OFFER_REDEMPTION_ML_WEIGHT = float(os.getenv("OFFER_REDEMPTION_ML_WEIGHT", "1.0"))
ROADMAP_NEXTSTEP_V4_SHADOW_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_SHADOW_MODEL_PATH",
    "",
).strip()
ROADMAP_NEXTSTEP_V4_HAIRCARE_RUNTIME_BIAS_ENABLED = env_bool(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_RUNTIME_BIAS_ENABLED",
    False,
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_RERANK_ENABLED = env_bool(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_RERANK_ENABLED",
    False,
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_LEAVEIN_RERANK_ENABLED = env_bool(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_LEAVEIN_RERANK_ENABLED",
    False,
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_RERANK_ENABLED = env_bool(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_RERANK_ENABLED",
    False,
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_MODEL_PATH",
    str(
        (
            BASE_DIR.parent
            / "models"
            / "roadmap_next_step_v5_planned_target_completed_14d_freshowned_haircare_cond_mask_60d"
            / "model.pkl"
        ).resolve()
    ),
).strip()
ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_WEIGHT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_WEIGHT", "0.75")
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_TARGETS = env_csv(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_CORECHAIN_TEACHER_TARGETS",
    "conditioner,hair_mask",
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_RERANK_ENABLED = env_bool(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_RERANK_ENABLED",
    False,
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_MODEL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_MODEL_PATH",
    str(
        (
            BASE_DIR.parent
            / "models"
            / "roadmap_next_step_scenario_scalp_hardcases_v2_r2"
            / "model.pkl"
        ).resolve()
    ),
).strip()
ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_WEIGHT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_WEIGHT", "0.75")
)
ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_TARGETS = env_csv(
    "ROADMAP_NEXTSTEP_V4_HAIRCARE_SCALP_TEACHER_TARGETS",
    "scalp_serum",
)
ROADMAP_SKU_HEALTH_PENALTY_ENABLED = env_bool(
    "ROADMAP_SKU_HEALTH_PENALTY_ENABLED",
    False,
)
ROADMAP_SKU_HEALTH_PENALTY_CATEGORIES = env_csv(
    "ROADMAP_SKU_HEALTH_PENALTY_CATEGORIES",
    "haircare",
)
ROADMAP_SKU_HEALTH_PENALTY_PRODUCT_TYPES = env_csv(
    "ROADMAP_SKU_HEALTH_PENALTY_PRODUCT_TYPES",
    "shampoo,conditioner",
)
ROADMAP_SKU_HEALTH_PENALTY_WINDOW_DAYS = int(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_WINDOW_DAYS", "60")
)
ROADMAP_SKU_HEALTH_PENALTY_MIN_RECOMMENDED_STEPS = int(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_MIN_RECOMMENDED_STEPS", "20")
)
ROADMAP_SKU_HEALTH_PENALTY_MAX_EXACT_ADOPTION_RATE = float(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_MAX_EXACT_ADOPTION_RATE", "0.01")
)
ROADMAP_SKU_HEALTH_PENALTY_MAX_EFFECTIVE_ADOPTION_RATE = float(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_MAX_EFFECTIVE_ADOPTION_RATE", "0.03")
)
ROADMAP_SKU_HEALTH_PENALTY_SEMANTIC_WEIGHT = float(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_SEMANTIC_WEIGHT", "0.25")
)
ROADMAP_SKU_HEALTH_PENALTY_MAX_VALUE = float(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_MAX_VALUE", "0.65")
)
ROADMAP_SKU_HEALTH_PENALTY_INCLUDE_GA = env_bool(
    "ROADMAP_SKU_HEALTH_PENALTY_INCLUDE_GA",
    False,
)
ROADMAP_SKU_HEALTH_PENALTY_CACHE_TTL_SECONDS = int(
    os.getenv("ROADMAP_SKU_HEALTH_PENALTY_CACHE_TTL_SECONDS", "1800")
)
ROADMAP_NEXTSTEP_V4_CONFIDENCE_THRESHOLD = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_CONFIDENCE_THRESHOLD", "0.10")
)
ROADMAP_NEXTSTEP_V4_UPLIFT_REPORT_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_UPLIFT_REPORT_PATH",
    str((BASE_DIR.parent / "reports" / "roadmap_ml_uplift_30d.json").resolve()),
)
ROADMAP_NEXTSTEP_V4_UPLIFT_REPORT_PATH_7D = os.getenv(
    "ROADMAP_NEXTSTEP_V4_UPLIFT_REPORT_PATH_7D",
    str((BASE_DIR.parent / "reports" / "roadmap_ml_uplift_7d.json").resolve()),
)
ROADMAP_NEXTSTEP_V4_UPLIFT_REPORT_PATH_30D = os.getenv(
    "ROADMAP_NEXTSTEP_V4_UPLIFT_REPORT_PATH_30D",
    str((BASE_DIR.parent / "reports" / "roadmap_ml_uplift_30d.json").resolve()),
)
ROADMAP_NEXTSTEP_V4_CATEGORY_MIN_PLANS = int(
    os.getenv("ROADMAP_NEXTSTEP_V4_CATEGORY_MIN_PLANS", "100")
)
ROADMAP_NEXTSTEP_V4_MIN_STEP_COMPLETION_LIFT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MIN_STEP_COMPLETION_LIFT", "0.01")
)
ROADMAP_NEXTSTEP_V4_MIN_OFFER_REDEEM_LIFT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MIN_OFFER_REDEEM_LIFT", "0.005")
)
ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_STEP_CTR_LIFT_SOFT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_STEP_CTR_LIFT_SOFT", "-0.02")
)
ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_OFFER_CTR_LIFT_SOFT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_OFFER_CTR_LIFT_SOFT", "-0.03")
)
ROADMAP_NEXTSTEP_V4_ALLOW_PRIMARY_WIN_DESPITE_SOFT_CTR_DROP = env_bool(
    "ROADMAP_NEXTSTEP_V4_ALLOW_PRIMARY_WIN_DESPITE_SOFT_CTR_DROP",
    True,
)
ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_STEP_CTR_LIFT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_STEP_CTR_LIFT", "-0.01")
)
ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_OFFER_CTR_LIFT = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MAX_NEGATIVE_OFFER_CTR_LIFT", "-0.01")
)
ROADMAP_NEXTSTEP_V4_MIN_LIFT_GUARD_ENABLED = env_bool(
    "ROADMAP_NEXTSTEP_V4_MIN_LIFT_GUARD_ENABLED",
    True,
)
ROADMAP_NEXTSTEP_V4_EVAL_PATH = os.getenv(
    "ROADMAP_NEXTSTEP_V4_EVAL_PATH",
    str((BASE_DIR.parent / "reports" / "roadmap_nextstep_v4_eval.json").resolve()),
)
ROADMAP_NEXTSTEP_V4_MIN_LIFT_METRIC = os.getenv(
    "ROADMAP_NEXTSTEP_V4_MIN_LIFT_METRIC",
    "ndcg_at_5",
).strip()
ROADMAP_NEXTSTEP_V4_MIN_LIFT_DELTA = float(
    os.getenv("ROADMAP_NEXTSTEP_V4_MIN_LIFT_DELTA", "0.01")
)
ROADMAP_PLANNER_V1_MODE = os.getenv("ROADMAP_PLANNER_V1_MODE", "off").strip().lower()
ROADMAP_PLANNER_V1_ENABLED_CATEGORIES = env_csv(
    "ROADMAP_PLANNER_V1_ENABLED_CATEGORIES",
    "",
)
ROADMAP_PLANNER_V1_MODEL_PATH = os.getenv(
    "ROADMAP_PLANNER_V1_MODEL_PATH",
    str((BASE_DIR.parent / "models" / "roadmap_planner_v1" / "model.pkl").resolve()),
)
ROADMAP_NEXTSTEP_CONFIDENCE_THRESHOLD = float(
    os.getenv("ROADMAP_NEXTSTEP_CONFIDENCE_THRESHOLD", "0.35")
)
ROADMAP_SUGGESTIONS_LIMIT = int(os.getenv("ROADMAP_SUGGESTIONS_LIMIT", "10"))
RECS_CO_MAP_PATH = os.getenv("RECS_CO_MAP_PATH", "").strip()
RECS_RERANKER_TOP_M = int(os.getenv("RECS_RERANKER_TOP_M", "1500"))
RECS_RERANKER_CONTEXT_K = int(os.getenv("RECS_RERANKER_CONTEXT_K", "10"))
RECS_RERANKER_HEURISTIC_POOL = int(os.getenv("RECS_RERANKER_HEURISTIC_POOL", "3000"))
RECS_RUNTIME_CO_DB_DAYS = int(os.getenv("RECS_RUNTIME_CO_DB_DAYS", "90"))
RECS_RUNTIME_CO_CACHE_TTL_SECONDS = int(os.getenv("RECS_RUNTIME_CO_CACHE_TTL_SECONDS", "600"))
RECS_RUNTIME_CO_EVENTS_DAYS = int(os.getenv("RECS_RUNTIME_CO_EVENTS_DAYS", "60"))
RECS_RUNTIME_CO_EVENTS_CACHE_TTL_SECONDS = int(os.getenv("RECS_RUNTIME_CO_EVENTS_CACHE_TTL_SECONDS", "600"))
RECS_RUNTIME_POPULARITY_DAYS = int(os.getenv("RECS_RUNTIME_POPULARITY_DAYS", "30"))
RECS_RUNTIME_POPULARITY_CACHE_TTL_SECONDS = int(os.getenv("RECS_RUNTIME_POPULARITY_CACHE_TTL_SECONDS", "600"))

# Retrieval mix settings (For You / Because)
RECS_RETRIEVAL_TOP_M = int(os.getenv("RECS_RETRIEVAL_TOP_M", "1500"))
RECS_RETRIEVAL_CONTEXT_K = int(os.getenv("RECS_RETRIEVAL_CONTEXT_K", "10"))
RECS_RETRIEVAL_PRODUCT_TYPE_FALLBACK_TOPN = int(os.getenv("RECS_RETRIEVAL_PRODUCT_TYPE_FALLBACK_TOPN", "400"))
RECS_RETRIEVAL_CATEGORY_FALLBACK_TOPN = int(os.getenv("RECS_RETRIEVAL_CATEGORY_FALLBACK_TOPN", "400"))
RECS_RETRIEVAL_BRAND_FALLBACK_TOPN = int(os.getenv("RECS_RETRIEVAL_BRAND_FALLBACK_TOPN", "400"))
RECS_RETRIEVAL_GLOBAL_FALLBACK_TOPN = int(os.getenv("RECS_RETRIEVAL_GLOBAL_FALLBACK_TOPN", "400"))

RECS_AB_ENABLED = env_bool("RECS_AB_ENABLED", False)
RECS_AB_RERANKER_PERCENT = int(os.getenv("RECS_AB_RERANKER_PERCENT", "50"))
RECS_AB_SALT = os.getenv("RECS_AB_SALT", "recs_ab_v1").strip()
RECS_AB_EXPERIMENT_ID = os.getenv("RECS_AB_EXPERIMENT_ID", "recs_algo_ab_v1").strip()

RECS_GUARDRAIL_ENABLED = env_bool("RECS_GUARDRAIL_ENABLED", False)
RECS_GUARDRAIL_WINDOW_DAYS = int(os.getenv("RECS_GUARDRAIL_WINDOW_DAYS", "7"))
RECS_GUARDRAIL_MIN_IMPRESSIONS = int(os.getenv("RECS_GUARDRAIL_MIN_IMPRESSIONS", "200"))
RECS_GUARDRAIL_MIN_DELTA_CR = float(os.getenv("RECS_GUARDRAIL_MIN_DELTA_CR", "-0.002"))
RECS_GUARDRAIL_CONTROL_ALGO = os.getenv("RECS_GUARDRAIL_CONTROL_ALGO", "cooc").strip().lower()
RECS_GUARDRAIL_TEST_ALGO = os.getenv("RECS_GUARDRAIL_TEST_ALGO", "reranker").strip().lower()
RECS_GUARDRAIL_CACHE_TTL_SECONDS = int(os.getenv("RECS_GUARDRAIL_CACHE_TTL_SECONDS", "60"))
