from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from backend.auth_views import (
    AuthCsrfView,
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    AuthPasswordResetConfirmView,
    AuthPasswordResetRequestView,
    AuthPasswordResetValidateView,
    AuthRegisterView,
    AuthResendVerificationView,
    AuthVerificationStatusView,
    AuthVerifyEmailView,
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("api/auth/csrf", AuthCsrfView.as_view(), name="auth-csrf"),
    path("api/auth/login", AuthLoginView.as_view(), name="auth-login"),
    path("api/auth/password-reset/request", AuthPasswordResetRequestView.as_view(), name="auth-password-reset-request"),
    path("api/auth/password-reset/validate", AuthPasswordResetValidateView.as_view(), name="auth-password-reset-validate"),
    path("api/auth/password-reset/confirm", AuthPasswordResetConfirmView.as_view(), name="auth-password-reset-confirm"),
    path("api/auth/register", AuthRegisterView.as_view(), name="auth-register"),
    path("api/auth/verify-email", AuthVerifyEmailView.as_view(), name="auth-verify-email"),
    path("api/auth/verify-email/resend", AuthResendVerificationView.as_view(), name="auth-resend-verification"),
    path("api/auth/verification-status", AuthVerificationStatusView.as_view(), name="auth-verification-status"),
    path("api/auth/logout", AuthLogoutView.as_view(), name="auth-logout"),
    path("api/auth/me", AuthMeView.as_view(), name="auth-me"),

    path("api/", include("catalog.urls")),
    path("api/", include("users_app.urls")),
    path("api/", include("routines.urls")),
    path("api/", include("transactions.urls")),
    path("api/", include("offers.urls")),
    path("api/", include("loyalty.urls")),
    path("api/", include("analytics_app.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/", include("recs_app.urls")),
    path("api/", include("checkout_app.urls")),
    path("api/", include("audit.urls")),
    path("api/", include("admin_tools.urls")),
    path("api/", include("recs_analytics.urls")),
    path("api/", include("roadmap_app.urls")),
]
