# Generated by Django 5.2.10 on 2026-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerassignment',
            name='redeemed_transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
