# Generated by Django 5.2.10 on 2026-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerassignment_redeemed_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignbudget',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
