# Generated by Django 5.2.10 on 2026-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_campaignbudget_week_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='allowed_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offer',
            name='allowed_product_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offer',
            name='target_scope',
            field=models.CharField(choices=[('cart', 'Cart'), ('category', 'Category'), ('product_type', 'Product type'), ('product_id', 'Product')], default='cart', max_length=20),
        ),
        migrations.AddField(
            model_name='offerassignment',
            name='target',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
