# Generated by Django 5.2.10 on 2026-01-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_allowed_categories_offer_allowed_product_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignbudget',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
