# Generated by Django 5.2.10 on 2026-02-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_campaignbudget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignbudget',
            name='allowed_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaignbudget',
            name='allowed_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaignbudget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignbudget',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.campaignbudget'),
        ),
    ]
