# Generated by Django 5.2.10 on 2026-02-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_campaignbudget_allowed_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expires_in_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
