# Generated by Django 5.2.10 on 2026-02-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_expires_in_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('offer_assigned', 'Offer assigned'), ('offer_exposed', 'Offer exposed'), ('offer_clicked', 'Offer clicked'), ('offer_redeemed', 'Offer redeemed'), ('offer_expired', 'Offer expired')], db_index=True, max_length=32)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='offers.offerassignment')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['campaign_name', 'created_at'], name='offers_offe_campaig_4c437d_idx'), models.Index(fields=['event_type', 'created_at'], name='offers_offe_event_t_3c3c49_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'event_type'), name='uq_offer_event_assignment_type')],
            },
        ),
    ]
