# Generated by Django 5.2.10 on 2026-02-26 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offerevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offerevent',
            name='uq_offer_event_assignment_type',
        ),
        migrations.AddField(
            model_name='offerevent',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='offerevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__isnull', False)), fields=('event_key',), name='uq_offer_event_key_not_null'),
        ),
    ]
