# Generated by Django 5.2.10 on 2026-02-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0009_remove_offerevent_uq_offer_event_assignment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerassignment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="offerassignment",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offerassignment",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_children",
                to="offers.offerassignment",
            ),
        ),
    ]
