# Generated by Django 5.2.10 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0010_offerassignment_is_active_offerassignment_superseded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("offer_assigned", "Offer assigned"),
                    ("offer_exposed", "Offer exposed"),
                    ("offer_clicked", "Offer clicked"),
                    ("offer_redeemed", "Offer redeemed"),
                    ("offer_expired", "Offer expired"),
                    ("offer_superseded", "Offer superseded"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
