# Generated by Django 5.2.10 on 2026-02-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_alter_product_volume_raw"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("skincare", "Skincare"), ("haircare", "Haircare"), ("makeup", "Makeup"), ("fragrance", "Fragrance"), ("mixed", "Mixed")], db_index=True, max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roadmap_plans", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_index", models.PositiveIntegerField()),
                ("product_type", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("missing", "Missing"), ("recommended", "Recommended"), ("owned", "Owned"), ("skipped", "Skipped"), ("completed", "Completed")], default="missing", max_length=20)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("score", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("why", models.JSONField(blank=True, default=list)),
                ("cadence", models.CharField(blank=True, choices=[("daily", "Daily"), ("weekly", "Weekly"), ("optional", "Optional")], default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="roadmap_app.roadmapplan")),
                ("recommended_product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="catalog.product")),
            ],
        ),
        migrations.AddIndex(
            model_name="roadmapplan",
            index=models.Index(fields=["user", "category", "is_active"], name="roadmap_app_user_id_d7a316_idx"),
        ),
        migrations.AddConstraint(
            model_name="roadmapstep",
            constraint=models.UniqueConstraint(fields=("plan", "step_index"), name="uq_roadmap_step_plan_index"),
        ),
        migrations.AddIndex(
            model_name="roadmapstep",
            index=models.Index(fields=["plan", "status"], name="roadmap_app_plan_id_4428b1_idx"),
        ),
    ]
