# Generated by Django 5.2.10 on 2026-02-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roadmapplan',
            new_name='roadmap_app_user_id_be9d4f_idx',
            old_name='roadmap_app_user_id_d7a316_idx',
        ),
        migrations.RenameIndex(
            model_name='roadmapstep',
            new_name='roadmap_app_plan_id_84e941_idx',
            old_name='roadmap_app_plan_id_4428b1_idx',
        ),
    ]
