# Generated by Django 5.2.10 on 2026-03-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap_app", "0002_rename_roadmap_app_user_id_d7a316_idx_roadmap_app_user_id_be9d4f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("roadmap_step_exposed", "Roadmap step exposed"),
                            ("roadmap_step_clicked", "Roadmap step clicked"),
                            ("roadmap_step_skipped", "Roadmap step skipped"),
                            ("roadmap_step_completed", "Roadmap step completed"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="roadmap_app.roadmapplan",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="roadmap_app.roadmapstep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="roadmapevent",
            index=models.Index(fields=["user", "created_at"], name="roadmap_app_user_id_06df4b_idx"),
        ),
        migrations.AddIndex(
            model_name="roadmapevent",
            index=models.Index(fields=["event_type", "created_at"], name="roadmap_app_event_t_b2de4d_idx"),
        ),
        migrations.AddIndex(
            model_name="roadmapevent",
            index=models.Index(fields=["step", "event_type"], name="roadmap_app_step_id_386a16_idx"),
        ),
    ]
