# Generated by Django 5.2.10 on 2026-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0003_roadmapevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapevent',
            name='event_type',
            field=models.CharField(choices=[('roadmap_plan_refreshed', 'Roadmap plan refreshed'), ('roadmap_step_generated', 'Roadmap step generated'), ('roadmap_step_exposed', 'Roadmap step exposed'), ('roadmap_step_clicked', 'Roadmap step clicked'), ('roadmap_step_skipped', 'Roadmap step skipped'), ('roadmap_step_completed', 'Roadmap step completed')], db_index=True, max_length=40),
        ),
    ]
