# Generated by Django 5.2.10 on 2026-04-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0004_alter_roadmapevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapMLInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('refresh_caller', models.CharField(blank=True, default='', max_length=64)),
                ('ml_mode', models.CharField(blank=True, default='', max_length=32)),
                ('decision', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('fallback_reason', models.CharField(blank=True, default='', max_length=64)),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=64)),
                ('model_path', models.CharField(blank=True, default='', max_length=512)),
                ('model_version', models.CharField(blank=True, default='', max_length=128)),
                ('model_slot', models.CharField(blank=True, default='', max_length=32)),
                ('predict_ms', models.FloatField(blank=True, null=True)),
                ('predict_error', models.CharField(blank=True, default='', max_length=512)),
                ('active_top_product_type', models.CharField(blank=True, default='', max_length=64)),
                ('active_top_score', models.FloatField(blank=True, null=True)),
                ('shadow_enabled', models.BooleanField(default=False)),
                ('shadow_reason', models.CharField(blank=True, default='', max_length=64)),
                ('shadow_model_path', models.CharField(blank=True, default='', max_length=512)),
                ('shadow_model_version', models.CharField(blank=True, default='', max_length=128)),
                ('shadow_predict_ms', models.FloatField(blank=True, null=True)),
                ('shadow_predict_error', models.CharField(blank=True, default='', max_length=512)),
                ('shadow_top_product_type', models.CharField(blank=True, default='', max_length=64)),
                ('shadow_top_score', models.FloatField(blank=True, null=True)),
                ('planner_mode', models.CharField(blank=True, default='', max_length=32)),
                ('planner_served', models.BooleanField(default=False)),
                ('planner_decision', models.CharField(blank=True, default='', max_length=20)),
                ('planner_model_path', models.CharField(blank=True, default='', max_length=512)),
                ('planner_predict_ms', models.FloatField(blank=True, null=True)),
                ('planner_predict_error', models.CharField(blank=True, default='', max_length=512)),
                ('rollout_mode', models.CharField(blank=True, default='', max_length=16)),
                ('rollout_selected', models.BooleanField(default=False)),
                ('rollout_bucket', models.IntegerField(blank=True, null=True)),
                ('rollout_percent', models.IntegerField(blank=True, null=True)),
                ('planned_target_product_type', models.CharField(blank=True, default='', max_length=64)),
                ('planned_target_step_index', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_invocations', to='roadmap_app.roadmapplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_ml_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'created_at'], name='roadmap_app_categor_c1d68b_idx'), models.Index(fields=['decision', 'created_at'], name='roadmap_app_decisio_537d4c_idx')],
            },
        ),
    ]
