# Generated by Django 5.2.10 on 2026-04-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0005_roadmapmlinvocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
    ]
