# Generated by Django 5.2.10 on 2026-01-08 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_ownedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ownedproduct',
            name='last_acquired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ownedproduct',
            name='quantity_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
