# Generated by Django 5.2.10 on 2026-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_idempotency_key_transaction_pricing_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedproduct',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedproduct',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ownedproduct',
            name='opened_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
