# Generated by Django 5.2.10 on 2026-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='fragrance_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='hair_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='makeup_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
