# Generated by Django 5.2.10 on 2026-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customerprofile_fragrance_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_completion_rewarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
