# Generated by Django 5.2.10 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0003_customerprofile_profile_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
