# Generated by Django 5.2.10 on 2026-01-27 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('checkout_created', 'Checkout Created'), ('checkout_replay', 'Checkout Replay'), ('offer_preview', 'Offer Preview'), ('offer_redeem', 'Offer Redeem'), ('next_offer_assigned', 'Next Offer Assigned'), ('cache_invalidate', 'Cache Invalidate')], max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=16, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='audit_audit_created_7710b7_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_39eebe_idx'), models.Index(fields=['request_id'], name='audit_audit_request_c59dc1_idx')],
            },
        ),
    ]
