# Generated by Django 5.2.10 on 2026-01-29 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_attrs_product_category_product_concerns_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('add_to_cart', 'Add To Cart'), ('purchase_attributed', 'Purchase Attributed')], max_length=32)),
                ('page', models.CharField(default='home', max_length=32)),
                ('section_key', models.CharField(blank=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('algo_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='recs_analyt_created_e6e5b7_idx'), models.Index(fields=['user', 'created_at'], name='recs_analyt_user_id_ec88c8_idx'), models.Index(fields=['action', 'created_at'], name='recs_analyt_action_78a393_idx'), models.Index(fields=['page', 'section_key', 'action', 'created_at'], name='recs_analyt_page_75363e_idx'), models.Index(fields=['product', 'action', 'created_at'], name='recs_analyt_product_9f925e_idx')],
            },
        ),
    ]
